name: Arduino Build

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Setup Environment
        run: cmake --build build --target setup

      - name: Build Tests
        run: cmake --build build --target run_tests

      - name: Run Tests
        run: ./build/tests/host/run_tests

      - name: Compile Sketch
        run: cmake --build build --target spresense
