name: Arduino Build

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      # ------------------------------------------------------------------------
      # Host Unit Tests
      # ------------------------------------------------------------------------
      - name: Configure CMake (Host Tests)
        run: cmake -S tests/host -B tests/host/build

      - name: Build Tests
        run: cmake --build tests/host/build

      - name: Run Tests
        run: ./tests/host/build/run_tests

      # ------------------------------------------------------------------------
      # Spresense Build
      # ------------------------------------------------------------------------
      - name: Configure CMake (Spresense)
        run: cmake -S . -B build

      - name: Setup Environment
        run: cmake --build build --target setup

      - name: Compile Sketch
        run: cmake --build build --target spresense
