name: Arduino Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Spresense Core
        run: |
          arduino-cli config init
          arduino-cli core update-index --additional-urls https://github.com/sonydevworld/spresense-arduino-compatible/releases/download/generic/package_spresense_index.json
          arduino-cli core install Spresense:spresense --additional-urls https://github.com/sonydevworld/spresense-arduino-compatible/releases/download/generic/package_spresense_index.json

      - name: Install Libraries
        run: |
          arduino-cli lib install LiquidCrystal

      - name: Compile Sketch
        run: arduino-cli compile --fqbn Spresense:spresense:spresense . --warnings all
